.github/workflows/github-pages.yml, package-lock.json
This pull request (PR) changes the trigger event for the GitHub Pages deployment workflow from push to on-demand. 
This gives the team the ability to deploy branches for review purposes. It's similar to the staging build, but gives us another environment to work with.
- n/a
- n/a
=> Deploy to gh-pages on demand

src/pages/guide/css/quickstart/compilation-mode.md
Fix grammatical error, "files are" rather than "file is".
-  https://developer.adobe.com/commerce/frontend-core/guide/css/quickstart/compilation-mode/
=> Fix grammatical error

src/pages/guide/best-practices.md
Add missing closing parenthesis: "(templates hints can help)" instead of "(templates hints can help".
This pull request (PR) adds a closing parenthesis after "(templates hints can help" to fix the syntax and improve readibility. 
-  [Theme development best practices](https://developer.adobe.com/commerce/frontend-core/guide/best-practices/)
-  [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
-  [x] My changes follow the code style of this project.
-  [x] I have read the **CONTRIBUTING** document.
-  [ ] All new and existing tests passed.
=> Fix missing parenthesis

src/pages/guide/layouts/xml-instructions.md
This pull request (PR) adds a note about making blocks cacheable.
https://github.com/AdobeDocs/commerce-frontend-core/blob/main/src/pages/guide/layouts/xml-instructions.md
https://github.com/magento/devdocs/pull/9471/files
=> Added note about non-caching blocks.

package.json, yarn.lock
This pull request (PR) bumps the theme to the latest version (4.4.2). We suspect it's the reason why the site search icon is not displaying.
- n/a
- n/a
=> Bump aio-theme to 4.4.2

.github/workflows/github-pages.yml, .github/workflows/test-pull-request.yml, package.json, yarn.lock
This pull request:
- Restores GitHub Actions workflow customizations that were reverted when the `aio-theme` dependency was bumped to v4.6.2.
- Pins the `gatsby-theme-aio` to v4.6.2 to prevent unexpected or untested releases/changes from breaking the site on each new deployment.
https://github.com/AdobeDocs/commerce-frontend-core/commit/b4f00b40588a02ae9f91d0bafeec740870340d97
See COMDOX-346 for details
See required checks in PR
N/A
=> COMDOX-346: Restore workflow customizations

gatsby-config.js, src/data/navigation/header.js, yarn.lock
This PR updates the navigation header by replacing the "Products" link with a link to our Commerce devdocs index page, named "Commerce."
COMDOX-340
The default "Products" header link is not useful for users of Commerce docs. Instead, we needed a link to the Commerce Developer docs main/index page.
Tested locally using by running `yarn start:prefix` and replacing `localhost:9000/commerce/docs/` with `https://developer.adobe.com/commerce/docs/` to ensure the new link is working. 
**Old navigation header:**
**New navigation header:**
=> Update navigation header to include link to Commerce devdocs index page

src/pages/guide/themes/index.md
Typo in doc : "or Sdmin) using" -> "or Admin) using"
https://developer.adobe.com/commerce/frontend-core/guide/themes/
Fixes #77
=> Typo "Sdmin"

src/pages/guide/css/ui-library.md
This pull request adds a link to the theme inheritance documentation where one appears to be intended.
[UI Library | Predefined Variables](https://developer.adobe.com/commerce/frontend-core/guide/css/ui-library/#predefined-variables)
=> Fix Link to Theme Inheritance Docs

src/data/navigation/sections/page_builder.js, src/pages/page-builder/known-limitations.md
Per discussion with the PO
- Add a new tab "Known Limitations" to the https://developer.adobe.com/commerce/frontend-core/page-builder/
New pages added:
- https://developer.adobe.com/commerce/frontend-core/page-builder/known-limitations/
N/A
=> ACP2E-1942: Create known-limitations page for PageBuilder

src/pages/guide/themes/product-video.md
This pull request (PR) is to add a note about the potential issue with product video autoplay caused by the browser policies. We must note that these policies are being frequently changed and we cannot guarantee that the video will play automatically as expected.
Same update I am posting to https://git.corp.adobe.com/AdobeDocs/commerce-admin.en/pull/212
- https://developer.adobe.com/commerce/frontend-core/guide/themes/product-video/
- https://jira.corp.adobe.com/browse/ACP2E-2187
=> ACP2E-2187: [Cloud] Youtube video autoplay is not working

src/pages/ui-components/components/color-picker.md
This pull request (PR) fixes #137.
- https://developer.adobe.com/commerce/frontend-core/ui-components/components/color-picker/
- n/a
=> Fix heading typo in ColorPicker UI component topic

src/pages/guide/responsive-design/css.md
This pull request (PR) is to resolve inconsistencies between a current system behavior of switching the layout between mobile and desktop modes being triggered at 768px width for mobile and 769px for desktop, as confirmed by the product manager and also, updated the code sample to reflect the current code.
- https://developer.adobe.com/commerce/frontend-core/guide/responsive-design/css/
- https://jira.corp.adobe.com/browse/ACP2E-2397
- https://jira.corp.adobe.com/browse/ACP2E-2281
- https://jira.corp.adobe.com/browse/ACP2E-169
=> ACP2E-2397: Update documentation for ACP2E-2281

src/pages/page-builder/upgrade-content-types.md
There is a misspelled word (`cms_blog`) on the example provided under `UpgradableEntitiesPool` entities node.
- https://developer.adobe.com/commerce/frontend-core/page-builder/upgrade-content-types/
- None
=> Correct misspelled word in upgrade-content-types.md

.remarkrc.mjs, package.json, src/pages/guide/css/debug.md, src/pages/page-builder/migration/install-migration-module.md, src/pages/ui-components/components/columns-controls.md, src/pages/ui-components/components/file-uploader.md, yarn.lock
This pull request (PR):
- Adds a plugin [remark-lint-no-dead-urls](https://github.com/remarkjs/remark-lint-no-dead-urls) to ensure that external URLs in Markdown pages are working. The linter returns warnings on https://www.php.net/ on working links in some reason (I assume server related issues) so I excluded this domain in the configuration.
- Replaces or removes dead links
Internal ticket: COMDOX-156
[Failed validate job](https://github.com/AdobeDocs/commerce-testing/actions/runs/6948160793/job/18903522012#step:11:12) reporting about dead links.
=> Add a linter to validate external links

.github/workflows/test-pull-request.yml, package.json, src/pages/javascript/index.md, src/pages/javascript/jquery-widgets/list.md, yarn.lock
This pull request (PR) upgrades theme to [v4.11.9](https://github.com/adobe/aio-theme/compare/%40adobe/gatsby-theme-aio%404.11.3...%40adobe/gatsby-theme-aio%404.11.9).
Jira: COMDOX-913
https://developer-stage.adobe.com/commerce/frontend-core/
=> Upgrade theme to v4.11.9

src/_includes/objects-in-templates.md, src/pages/guide/layouts/xml-instructions.md, src/pages/guide/templates/override.md
This pull request (PR) is to add a note to technical guidelines about instantiation of the new objects from templates to avoid confusion.
**Please note I am keeping this as draft for collaboration between developers to edit and approve and will change the status once we will be done. Thanks.**
Related PR: https://github.com/AdobeDocs/commerce-php/pull/261
- https://developer.adobe.com/commerce/frontend-core/guide/templates/override/#getting-argument-values-from-layout
- https://developer.adobe.com/commerce/frontend-core/guide/layouts/xml-instructions/#obtain-arguments-examples-in-template
=> ACP2E-3031: Update the documentation on OM in templates

src/pages/guide/responsive-design/css.md
This pull request (PR) is to rollback the change from https://github.com/AdobeDocs/commerce-frontend-core/pull/136 since the decision has been changed by the PM regarding the breakpoints that toggle mobile<>desktop layouts.
I am targeting 2.4.8-develop here since the changes won't be released until then.
https://jira.corp.adobe.com/browse/ACP2E-2966
- https://developer.adobe.com/commerce/frontend-core/guide/responsive-design/css/
- ...
=> ACP2E-3042: Update the documentation on mobile/ desktop breakpoints (rollback previous changes)

.remarkrc.mjs, package.json, src/pages/page-builder/contributors.md, yarn.lock
This pull request (PR) upgrades theme to [v4.11.14](https://github.com/adobe/aio-theme/compare/%40adobe/gatsby-theme-aio%404.11.9...adobe/gatsby-theme-aio%404.11.14).
https://developer-stage.adobe.com/commerce/frontend-core/
=> Upgrade theme to v4.11.14

src/pages/guide/css/preprocess.md
This pull request (PR) adds some minor formatting to the content added in #180.
- https://developer.adobe.com/commerce/frontend-core/guide/css/preprocess/#magento_import-directive
=> Minor formatting for #180

src/pages/guide/caching.md, src/pages/guide/themes/apply-admin.md, src/pages/guide/themes/create-storefront.md, src/pages/guide/themes/install.md, src/pages/guide/themes/product-video.md, src/pages/guide/themes/uninstall.md, src/pages/guide/translations/dictionary.md, src/pages/guide/translations/index.md, src/pages/index.md, src/pages/page-builder/content-types/create/add-form.md, src/pages/page-builder/content-types/customize/add-icons-images.md, src/pages/page-builder/contributors.md, src/pages/page-builder/migration/how-content-migration-works.md, src/pages/page-builder/migration/install-migration-module.md, src/pages/page-builder/migration/migrate-content-custom-blocks.md, src/pages/ui-components/howto/add-category-attribute.md
This pull request (PR) replaces links to decommissioned resources with final destinations.
- https://developer.adobe.com/commerce/frontend-core/guide/caching/
- https://developer.adobe.com/commerce/frontend-core/guide/themes/apply-admin/
- https://developer.adobe.com/commerce/frontend-core/guide/themes/create-storefront/
- https://developer.adobe.com/commerce/frontend-core/guide/themes/install/
- https://developer.adobe.com/commerce/frontend-core/guide/themes/product-video/
- https://developer.adobe.com/commerce/frontend-core/guide/themes/uninstall/
- https://developer.adobe.com/commerce/frontend-core/guide/translations/dictionary/
- https://developer.adobe.com/commerce/frontend-core/guide/translations/index/
- https://developer.adobe.com/commerce/frontend-core/index/
- …
=> Update links to decommissioned resources

src/pages/guide/layouts/types.md, src/pages/guide/themes/create-admin.md, src/pages/guide/themes/create-storefront.md, src/pages/page-builder/content-types/customize/index.md, src/pages/page-builder/migration/how-content-migration-works.md, src/pages/page-builder/upgrade-content-types.md, src/pages/ui-components/components/url-input.md, src/pages/ui-components/components/wysiwyg/add-custom-editor.md, src/pages/ui-components/components/wysiwyg/extension-points.md, src/pages/ui-components/components/wysiwyg/index.md, src/pages/ui-components/concepts/xml-declaration.md, src/pages/ui-components/howto/update-url-type.md
This pull request (PR) updates the copyright in code samples.
- https://developer.adobe.com/commerce/frontend-core/guide/layouts/types/
- https://developer.adobe.com/commerce/frontend-core/guide/themes/create-admin/
- https://developer.adobe.com/commerce/frontend-core/guide/themes/create-storefront/
- https://developer.adobe.com/commerce/frontend-core/page-builder/content-types/customize/
- https://developer.adobe.com/commerce/frontend-core/page-builder/migration/how-content-migration-works/
- https://developer.adobe.com/commerce/frontend-core/page-builder/upgrade-content-types/
- https://developer.adobe.com/commerce/frontend-core/ui-components/components/url-input/
- https://developer.adobe.com/commerce/frontend-core/ui-components/components/wysiwyg/add-custom-editor/
- …
=> Update the copyright in code samples
