- src/data/navigation/sections/frontend.js
- src/pages/guide/css/custom-preprocessor/gulp-sass.md
- src/pages/guide/layouts/create.md
- src/pages/guide/layouts/extend.md
- src/pages/guide/templates/sample.md
This pull request (PR) add follow-up fixes found during [PR #3028](https://github.com/magento-commerce/devdocs/pull/3028) review
> Add follow-up fixes found during PR #3028 review

- src/pages/guide/caching.md
This pull request (PR) fixed a typo.
-  ...
-  ...
-  [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
-  [x] My changes follow the code style of this project.
-  [x] I have read the **CONTRIBUTING** document.
-  [x] All new and existing tests passed.
> info updated

- .github/workflows/test-pull-request.yml
#	.github/workflows/test-pull-request.yml
This pull request (PR) ...
-  ...
-  ...
-  [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
-  [ ] My changes follow the code style of this project.
-  [ ] I have read the **CONTRIBUTING** document.
-  [ ] All new and existing tests passed.
> fix: separate pull-request validation steps to fix build

- .github/linters/.yaml-lint.yml
- .github/scripts/get-path-prefix.js
- .github/workflows/deploy.yml
- .github/workflows/github-pages.yml
- .github/workflows/test-pull-request.yml
- README.md
- gatsby-config.js
This pull request (PR) attempts to set an initial standard for the `AdobeDocs/dev-site-documentation-template`. Consider this a proposal for standardizing the `.github` files for the template. 
README page was update with status entries
> Updated workflows to serve as standard for devsite templates

- src/pages/ui-components/components/checkbox-toggle-notice.md
- src/pages/ui-components/concepts/index.md
- src/pages/ui-components/howto/add-category-attribute.md
- src/pages/ui-components/howto/new-component-declaration.md
This pull request (PR) fixes a few typos I noticed in our migration work from yesterday.
See files diff. 
NA
> Spelling fixes

- src/pages/guide/validations/custom-rules.md
This pull request (PR) fixes an incorrect javascript example.
https://developer.adobe.com/commerce/frontend-core/guide/validations/custom-rules/
Copy of https://github.com/magento/devdocs/pull/9464
> Updated incorrect code sample

- src/pages/guide/translations/dictionary.md
Duplicate O on Override
This pull request (PR) ...
- ...
- ...
> Typo spotted

- src/pages/guide/css/ui-library.md
This pull request (PR) fixes the grammatical error, "UI library" rather than "UI libraary".
- https://developer.adobe.com/commerce/frontend-core/guide/css/ui-library/
> Fix gramatical error

- src/pages/page-builder/viewports/add-breakpoints.md
While adding metadata, I noticed one page started with an H2.
> Heading level fix

- src/pages/guide/css/index.md
- Add missing application name - Adobe Commerce and Magento Source 
- Remove extra white space in the summary and an extraneous dash
This PR fixes editorial issues in the Cascading Style Sheet topic.
> Editorial fixes

- .github/workflows/add-to-project-board.yml
This PR adds a GitHub workflow to add Pull Requests and Issues to the Commerce project boards.
See [the Docs wiki](https://wiki.corp.adobe.com/display/MDOC/GitHub+Queue+Management#GitHubQueueManagement-Projects).
> COMDOX-372 Add workflow for issues and prs

- src/pages/page-builder/content-types/create/add-templates.md
Fixes the docs to use correct code. For more info see https://github.com/magento/magento2/issues/35501 and https://github.com/magento/magento2/issues/35501#issuecomment-1135629580.
The current example does not work properly. The options are displayed but nothing more is rendered afterwards.
Tested in a custom content-type. You can find an official example here: https://github.com/magento/magento2-page-builder/blob/develop/app/code/Magento/PageBuilder/view/adminhtml/web/template/content-type/image/full-width/preview.html#L9
> Use closing tag to fix template example

- src/pages/guide/translations/practice.md
Fixes #68.
Fix the example narrative to show the image with the default string values in the introduction. Move the image with the customized value to the results section to show the effect of adding custom strings to a theme.
Fixes #68.
Corrects the example demonstrating how to customize strings in for a storefront theme.
Reviewed current topic and put images in correct order to show image with default strings that are updated by theme customizations followed by the image of how the default strings change when the custom theme is applied.
- Documentation change
> Correct image examples

- src/pages/page-builder/content-types/customize/add-custom-toolbar.md
- src/pages/page-builder/content-types/extend/add-appearances.md
- src/pages/page-builder/content-types/extend/extend-appearances.md
- src/pages/page-builder/content-types/extend/extend-more-appearances.md
- src/pages/page-builder/pagebuilder-examples.md
- src/pages/page-builder/viewports/add-viewports.md
Rename magento-devdocs to commerce-docs.
> Rename magento-devdocs to commerce-docs in links

- .github/workflows/deploy.yml
Extend memory allocation size to fix a deployment failure `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`.
This is a known issue that was fixed in other projects.
> Fix deployment issue with memory allocation

- src/pages/javascript/jquery-widgets/index.md
This pull request (PR) updates jQuery UI version to match the current version the application supports
- https://developer.adobe.com/commerce/frontend-core/javascript/jquery-widgets/
- https://github.com/magento/magento2/blob/2.4.6-p2/lib/web/jquery/jquery-ui.js
> Update jQuery UI version to match the current version

- .github/workflows/index.yml
This pull request (PR) updates the indexing GitHub Action workflow to match the workflow in the [commerce-php](https://github.com/AdobeDocs/commerce-php/blob/main/.github/workflows/index.yml) repo.
The indexing workflow in the [AdobeDocs/commerce-frontend-core](https://github.com/AdobeDocs/commerce-frontend-core/actions/workflows/index.yml) repo has been failing for the last 6 months.
> Increase memory to fix indexing workflow failures

- src/pages/javascript/jquery-widgets/quick-search.md
Update doc according to the information shared in [ACP2E-3050](https://jira.corp.adobe.com/browse/ACP2E-3050)
/pages/javascript/jquery-widgets/quick-search.md
- ...
> ACP2E-3107: Documentation Update Quick Search with OpenSearch Analyzer

- src/pages/guide/layouts/types.md
- src/pages/guide/themes/create-admin.md
- src/pages/guide/themes/create-storefront.md
- src/pages/page-builder/content-types/customize/index.md
- src/pages/page-builder/migration/how-content-migration-works.md
- src/pages/page-builder/upgrade-content-types.md
- src/pages/ui-components/components/url-input.md
- src/pages/ui-components/components/wysiwyg/add-custom-editor.md
- src/pages/ui-components/components/wysiwyg/extension-points.md
- src/pages/ui-components/components/wysiwyg/index.md
- src/pages/ui-components/concepts/xml-declaration.md
- src/pages/ui-components/howto/update-url-type.md
This pull request (PR) updates the copyright header in code samples.
> Update copyright in code samples

- src/pages/guide/css/preprocess.md
This pull request (PR) removes a reference to 2.4.8-beta.
> COMDOX-167: Removed reference to beta'
